### ISSUE TITLE
Adding bold to links break on reading view

### ISSUE THREAD

**Issue by luabagg** [bennyxguo/Obsidian-Obsidianite#109]
Both normal and wikilinks break on reading view:

#### Editing:
<img width="420" alt="Image" src="https://github.com/user-attachments/assets/912262c4-c150-4f31-a0aa-cd065538c505" />

#### Reading:
<img width="285" alt="Image" src="https://github.com/user-attachments/assets/51ec5e74-b7b0-4bcf-93e1-d279d9c3736d" />

**Wiki Links**

#### Editing:
<img width="253" alt="Image" src="https://github.com/user-attachments/assets/8b656d6c-f69e-4a30-9d75-9ba43dd65385" />

#### Reading:
<img width="442" alt="Image" src="https://github.com/user-attachments/assets/f5e95ae3-c48c-4961-a55f-3f176cead720" />

Since I'm using Waypoint this is kinda annoying since bold links are default. This also breaks bold links in the "Obsidian Digital Garden" plugin

**Comment by jeykey** [comment]
I had the same problem with links in tables and bullet points.
Fixed it by addidng this to the css:

```css
/**
 * FIX: Bold links in lists, tables, etc.
 */
strong :is(a.internal-link, a.external-link),
.cm-strong :is(.cm-hmd-internal-link, .cm-link) .cm-underline {
  -webkit-text-fill-color: transparent;
  -webkit-background-clip: text;
  background-clip: text;
  background: linear-gradient(62deg, #87c2fd 0%, #dcb9fc 100%) text !important;
  text-decoration: none !important;
  position: relative;
}

/** Underline via ::after — matches normal link background-image underline */
strong :is(a.internal-link, a.external-link)::after {
  content: "";
  position: absolute;
  inset: auto 0 0;
  height: 5px;
  background: repeat-x 0 100% / 5px 5px
    linear-gradient(to bottom, var(--underline-color) 0%, var(--underline-color) 100%);
  pointer-events: none;
}

strong a.internal-link {
  --underline-color: var(--bg-accent-55);
  --hover-bg-color: var(--bg-accent-55);
}

strong a.external-link {
  --underline-color: var(--bg-sub-accent-55);
  --hover-bg-color: var(--bg-sub-accent-55);
}

/** Hover highlight via ::before */
strong :is(a.internal-link, a.external-link)::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: -1;
  border-radius: 2px;
  background: var(--hover-bg-color);
  opacity: 0;
  transform: scaleY(0);
  transform-origin: bottom;
}

strong :is(a.internal-link, a.external-link):hover,
.cm-strong :is(.cm-hmd-internal-link, .cm-link) .cm-underline:hover {
  -webkit-text-fill-color: #fff;
  -webkit-background-clip: initial;
  background-clip: initial;
  background: none !important;
}

strong :is(a.internal-link, a.external-link):hover::after {
  opacity: 0;
}

strong :is(a.internal-link, a.external-link):hover::before {
  opacity: 1;
  transform: scaleY(1);
}
```
