### ISSUE TITLE
Bullet lists in edit mode not compatible with different fonts

### ISSUE THREAD

**Issue by OscarAblinger** [bennyxguo/Obsidian-Obsidianite#32]
I'm using the Obsidianite theme but wanted to change the fonts. Sadly that introduced a visual bug with the bullets.
For one the bullet was halved. And the not-focused lines would also be moved a bit to the right, making vertical movements slightly more annoying.

I understand that you don't necessarily support different fonts, so feel free to close this issue again.
However, since I fixed it in a quick CSS snippet, I figured that it might be useful to some people:

```css
div:not(.CodeMirror-activeline) > .CodeMirror-line span.cm-formatting-list-ul {
    text-indent: inherit !important;
    white-space: inherit !important;
    min-width: inherit !important;
    visibility: hidden;
}

div:not(.CodeMirror-activeline) > .CodeMirror-line span.cm-formatting-list-ul::after {
    left: 0 !important;
    visibility: visible;
}
```

All of the `!important` styles only overwrite some of the Obsidianite CSS, so if it was integrated into the theme, you would just remove the lines that originally change those properties.
Essentially, instead of adding a dot after the text and then moving it a fixed amount to the left, I just added the dot at the start of the line on top and just made the normal text invisible.
That way it __should__ be compatible with any font.

For reference:
With out the fix:
![grafik](https://user-images.githubusercontent.com/25868587/123175300-dedfa300-d481-11eb-8381-a3039e1edac5.png)
With the fix:
![grafik](https://user-images.githubusercontent.com/25868587/123175313-e901a180-d481-11eb-9a9d-a04d2cab5dc5.png)
It also works with the default fonts:
![grafik](https://user-images.githubusercontent.com/25868587/123175657-6b8a6100-d482-11eb-8c77-c45e3cfc12b6.png)
