### ISSUE TITLE
Shadow with Sliding Panes

### ISSUE THREAD

**Issue by zcysxy** [bennyxguo/Obsidian-Obsidianite#35]
Hi Tridiamond! I found a tiny bug I don't know whether it's a known issue or not. That is, when Sliding Panes mode is on and there is only one pane, strange shadow effects appear on the view-header. Such shadow will not appear when there are more than one panes.

<img src="https://user-images.githubusercontent.com/48207708/129176609-b51c95e5-8ed1-4317-ab37-3ef9e4ba8656.png" height=500px>

**Comment by zcysxy** [comment]
Emmm it's actually caused by the plugin (Sliding Panes) itself, and such problem appears in some other themes as well. I fixed it using

```css
.view-header-title-container::before, .view-header-title-container::before { background: none !important }
```

Don't know if other elements will be affected yet. If not maybe you can consider adding this to your theme ;)
