### ISSUE TITLE
Strange block that hides top of the page in edit mode

### ISSUE THREAD

**Issue by januszj** [bennyxguo/Obsidian-Obsidianite#47]
Hi,

There is strange block that hides top of the page in edit mode:
![image](https://user-images.githubusercontent.com/1262428/156577097-6ec5783a-ca56-4d64-aadc-7381271ea75c.png)
Only visible with this theme.
When in preview mode it disapears.

**Comment by larsmew** [comment]
Hi,

I also experience the same issue when inserting a code block into a note. Otherwise, I haven't experienced this issue.
![Skærmbillede 2022-03-10 kl  00 33 13](https://user-images.githubusercontent.com/2529216/157557419-68299377-bb3a-4b39-93f2-c895e63ad922.png)

![Skærmbillede 2022-03-10 kl  00 33 23](https://user-images.githubusercontent.com/2529216/157557416-f7166b2c-8bda-4346-87b8-5ef5cbf5b861.png)

Would really love a fix for this!

**Comment by peachsativa** [comment]
I am also having this issue on Ubuntu 20.04

This is my favorite theme by far and I do a lot of coding so I would like this to be fixed as well!

**Comment by TibixDev** [comment]
I am also having the exact same issue, anyone any tips?

**Comment by Chen-913** [comment]
I just ran into this problem too, maybe it's because I don't know how to write with this style of code block.
But I found the corresponding class to make it disappear by debugging tool .
First open the theme's css file and just comment out the following code.
You can use the shortcut Ctrl+F to find them.
```css
.cm-s-obsidian pre.HyperMD-codeblock {
  color: var(--text-sub-accent);
}

.cm-s-obsidian div.HyperMD-codeblock-bg {
  background-color: #191621;
}

.cm-s-obsidian div.HyperMD-codeblock-begin-bg {
  border-top-left-radius: 0.3em;
  border-top-right-radius: 0.3em;
  border: none;
}

.cm-s-obsidian div.HyperMD-codeblock-begin-bg:before {
  position: absolute;
  content: '';
  top: -5%;
  left: 0;
  width: 100%;
  height: 60%;
  border-top-left-radius: 0.3em;
  border-top-right-radius: 0.3em;
  background-color: #191621;
} 
```
Of course if there is a way to do this without changing the source code, or if this is a bug, please let me know, thank you very much!
