### ISSUE TITLE
The border line of the table is not visible in dark mode

### ISSUE THREAD

**Issue by Chen-913** [bennyxguo/Obsidian-Obsidianite#48]
The problem is as described in the title, which makes it impossible for me to carefully distinguish each item corresponding to the table

![image](https://user-images.githubusercontent.com/72293244/159104398-70dd55ae-8941-4820-ac42-eaf7d969b2d5.png)

Even if I turn off the transparent background, the color of the table borders is still not very distinguishable

Could you tell me how to modify it?

**Comment by Chen-913** [comment]
I found the style of the table border through devtools as follows.
```css
.markdown-preview-view th, .markdown-preview-view td{
	border: 1px solid rgb(255 255 255 / 50%);
}
```
Then I successfully modified it.

**Comment by fstlaneukraine** [comment]
I'm having the same issue but creating a snippet with the above style doesn't seem to do anything.

**Comment by gucovip** [comment]
Obsidian version 1.5.3
```css
.table-editor th,
.table-editor td,
.table-editor thead tr>th {
	border: 1px solid rgba(255, 255, 255, 0.3);
}

.markdown-reading-view th,
.markdown-reading-view td,
.markdown-reading-view thead tr>th {
	border: 1px solid rgba(255, 255, 255, 0.3);
}
```
