### ISSUE TITLE
there is a problem with code block here.

### ISSUE THREAD

**Issue by buthow-top** [bennyxguo/Obsidian-Obsidianite#52]
[like this](https://sm.ms/image/LzQX3FyhilwGRC7)

it can be fixed like this,change top:-5% to -60%

.cm-s-obsidian div.HyperMD-codeblock-begin-bg:before {
  position: absolute;
  content: '';
  top: -60%;
  left: 0;
  width: 100%;
  height: 60%;
  border-top-left-radius: 0.3em;
  border-top-right-radius: 0.3em;
  background-color: #191621;
}

**Comment by AzadKshitij** [comment]
I was having some issues even after applying the snippet 
This is what worked for me
```css
.cm-s-obsidian div.HyperMD-codeblock-begin-bg:before {
  position: absolute;
  content: "";
  width: 100%;
  height: 100%;
  margin-top: 1.5em;
  border-top-left-radius: 0.3em;
  border-top-right-radius: 0.3em;
  background-color: #191621;
}
```
