### ISSUE TITLE
Alignment of list items

### ISSUE THREAD

**Issue by krokofant** [bennyxguo/Obsidian-Obsidianite#71]
```markdown
- hello
	- dwdqw
	- [ ] foo
		- [ ] 
	- hello
		- foo
	- bar
```

This is rendered like this for me
![image](https://user-images.githubusercontent.com/5908498/198697077-da106f26-5f05-4ea8-8d4c-252cf7db06ea.png)

Here is another which highlights the alignment
![image](https://user-images.githubusercontent.com/5908498/198697791-58af8963-38c7-4009-9b43-1b6fc92c64b7.png)

If I apply these css changes:
```css
.markdown-source-view.mod-cm6 .list-bullet:after {
  transform: translate(35%, -50%);
}

.HyperMD-list-line:not(.HyperMD-task-line) span[class^="cm-list-"]::before {
  content: "\00A0";
}
```

Then it looks like this
![image](https://user-images.githubusercontent.com/5908498/198697966-1337516e-e091-4006-8eba-aa772b0f8585.png)
![image](https://user-images.githubusercontent.com/5908498/198698070-2f3cd571-f202-4037-8418-041448cd4bc0.png)

Can I submit a PR for these changes @bennyxguo ?
