### ISSUE TITLE
Can't complete tasks inside task queries (Tasks Plugin)

### ISSUE THREAD

**Issue by Stuff1014** [bennyxguo/Obsidian-Obsidianite#99]
Howdy!
I'm using the Tasks plugin and am having an issue with queries. I can't complete tasks from a query like I can on base Obsidian or other themes. In the second image, when I click on the checkbox created by the query, nothing happens. This theme looks great! Thanks!
---
<img width="569" alt="Screenshot 2023-12-19 121853" src="https://github.com/bennyxguo/Obsidian-Obsidianite/assets/154365552/097df39e-e1ba-4f0f-8825-a350339f6cb0">

<img width="581" alt="Screenshot 2023-12-19 121911" src="https://github.com/bennyxguo/Obsidian-Obsidianite/assets/154365552/604a2a48-dd9c-41fe-9dc6-c966123e324a">

**Comment by aparente** [comment]
I'm having the same problem!

**Comment by krokofant** [comment]
Please provide the markdown in the issue like
``````
```markdown
- example
```
``````

So it's easier to quickly replicate the issue.

**Comment by Stuff1014** [comment]
- [ ] Sample Task  [due:: 2024-01-14]
```tasks
Due Today
Not Done
```

**Comment by Stuff1014** [comment]
\- [ ] Sample Task  [due:: 2024-01-14]
\```tasks
Due Today
Not Done
\```

**Comment by tobybaratta** [comment]
Hi - just wanted to +1 this issue!

**Comment by EmilianC** [comment]
Same issue here. I noticed that the check boxes are there and completable, but they exist in the whitespace between the visible box and the text. The visual is in the incorrect spot, as the theme.css hides the "real" checkbox and creates another one in the wrong place.

I was able to get a satisfactory result by commenting out the following two blocks from the theme.css manually.

```css
//...
// line 386
/*
.contains-task-list .task-list-item input[type='checkbox'] {
  position: relative;
  top: 2px;
  left: -8px;
  width: 20px;
  height: 20px;
  margin: 0;
  opacity: 0;
  z-index: 10;
}
*/
```

```css
//...
// line 404
/*
.contains-task-list .task-list-item::before {
  content: '';
  position: absolute;
  top: 2px;
  left: -25px;
  width: 20px;
  height: 20px;
  display: inline-flex;
  justify-content: center;
  border: 2px solid #9e9e9e;
  margin-right: 15px;
  border-radius: 3px;
  transition: all 0.3s;
  box-sizing: border-box;
  z-index: 1;
}
*/
```

<img width="825" height="319" alt="Image" src="https://github.com/user-attachments/assets/f4e5ec64-c143-4a89-b528-028176f23cfb" />
